<?php

namespace L1m2\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ExtraitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtraitRepository extends PropoRepository
{
    protected function getStatusQuery($status, $order)
    {      
        $qb = $this->createQueryBuilder('e');
        
        if ($status != Proposition::STATUS_TOUT) 
        {
            $qb->where('e.status = :status')            
               ->setParameter('status', $status);
        }
        
        if ($order == Proposition::DATE_DESC) 
        {
            $qb->orderBy('e.datePropo', 'DESC');
        }
        elseif ($order == Proposition::DATE_ASC) 
        {
            $qb->orderBy('e.datePropo', 'ASC');
        }
        elseif ($order == Proposition::LEN_DESC) 
        {
            $qb->addOrderBy($qb->expr()->length('e.entrees'), 'DESC');
        }
        else
        {
            $qb->addOrderBy($qb->expr()->length('e.entrees'), 'ASC');
        }
            
        return $qb->getQuery();
    }
}
