<?php

namespace L1m2\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ExtraitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtraitRepository extends PropoRepository
{
    protected function getStatusQuery($status)
    {
        $qb = $this->createQueryBuilder('e');
        if ($status != Proposition::STATUS_TOUT) 
        {
            $qb->where('e.status = :status')            
               ->setParameter('status', $status);
        }
        $query = $qb->orderBy('e.datePropo', 'DESC')
                    ->getQuery()
        ;
        return $query;
    }
}
