<?php

namespace L1m2\PlatformBundle\Entity;
use Doctrine\ORM\QueryBuilder;

/**
 * TransfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransfoRepository extends PropoRepository
{
    protected function getStatusQuery($status)
    {
        $qb = $this->createQueryBuilder('t');
        if ($status != Proposition::STATUS_TOUT) 
        {
            $qb->where('t.status = :status')            
               ->setParameter('status', $status);
        }
        $query = $qb->orderBy('t.datePropo', 'DESC')
                    ->getQuery()
        ;
        return $query;
    }


}
